---
toc: false
---

<center>
## Peer-reviewed publications and articles
</center>

<br>

<center>
### COVID
</center>

[Treating Covid-19 - When enthusiasm trumps evidence](https://ojo-publico.com/1903/treating-covid-19-when-enthusiasm-trumps-evidence) (2020). **Martin Frigaard** & Aleszu Bajak. *OjoPublico*. 

<center>
### Chronic Kidney Disease
</center>

[Screening for CKD To Improve Processes of Care among Nondiabetic Veterans with Hypertension](https://doi.org/10.2215/CJN.05050419) (2020). Carmen A Peralta, **Martin Frigaard**, Leticia Rolon, Karen Seal, Delphine Tuot, Josh Senyak, Lowell Lo, Neil Powe, Rebecca Scherzer, Shirley Chao, Phillip Chiao, Kimberly Lui, Michael G Shlipak, and Anna D Rubinsky. *Clinical Journal of the American Society of Nephrology*. 

[Validating laboratory defined chronic kidney disease in the electronic health record for patients in primary care](https://link.springer.com/article/10.1186/s12882-018-1156-2) (2019). **Martin Frigaard**, Anna Rubinsky, Lo Lowell, Anna Malkina, Leah Karliner, Michael Kohn, Carmen A Peralta. *BMC Nephrology*.	

[The Associations Between CKD Diagnosis and Guideline Driven Care](https://www.ajkd.org/article/S0272-6386(18)30232-4/abstract) (2018). **Martin James Frigaard**, Leah Karliner, Carmen Peralta. *American Journal of Kidney Diseases*.

[Comparison of Historical Lab CKD and Clinician Chart Review](https://www.ajkd.org/article/S0272-6386(18)30231-2/abstract) (2018). **Martin James Frigaard**, Leah Karliner, Carmen Peralta. *American Journal of Kidney Diseases*.

[Implementation of a pragmatic randomized trial of screening for chronic kidney disease to improve care among non-diabetic hypertensive veterans](https://link.springer.com/article/10.1186/s12882-017-0541-6) (2017). Carmen A Peralta, **Martin Frigaard**, Anna D Rubinsky, Leticia Rolon, Lowell Lo, Santhi Voora, Karen Seal, Delphine Tuot, Shirley Chao, Kimberly Lui, Phillip Chiao, Neil Powe, Michael Shlipak. *BMC Nephrology*.

<center>
### Nutrition
</center>

[Behavioral economics and social marketing campaign increases selection and consumption of school lunch garden bar Items among elementary school students](https://doi.org/10.1096/fasebj.28.1_supplement.1019.19) (2014). Joshua Andre, Cindy Wolff, Keiko Goto, Stephanie Bianco, **Martin Frigaard**, Garth Hansen, Rachel Riley, Sheila St. Cin *The Federation of American Societies for Experimental Biology*.

[“We can make a difference”: The Nourish Curriculum facilitates middle‐school students’ sustainable and healthy food choices](https://doi.org/10.1096/fasebj.28.1_supplement.626.18) (2014). Keiko Goto, Emily Ramsey, Cindy Wolff, Alyson Wylie, Stephanie Bianco‐Simeral, Rachel Riley, **Martin Frigaard**, Joshua Andre. *The Federation of American Societies for Experimental Biology*.

[The nutritional moral of the story: An examination of storybooks used to promote healthy food-choice behavior]() (2014). Ben Seipel, SE Carlson, Stephanie Bianco-Simeral, **Martin Frigaard**, Cindy Wolff, K Goto. *Psychology and Education: An Interdisciplinary Journal*.

[The Harvest of the Month (HOTM) program successfully promotes vegetable selection and consumption among first graders from low‐income schools](https://doi.org/10.1096/fasebj.27.1_supplement.843.4) (2013). Qiong Chen, Amanda Gerson, Keiko Goto, Cindy Wolff, Stephanie Bianco‐Simeral, Garth Hansen, **Martin Frigaard**, Ben Armstrong. *The Federation of American Societies for Experimental Biology*.

[The impact of a multicomponent school-based program on fruit and vegetable selection from school salad bars among K-6 grade students](https://www.jneb.org/article/S1499-4046(12)00270-9/abstract) (2012).  Keiko Goto, Cindy Wolff, **Martin Frigaard**, Stephanie Bianco-Simeral. *Journal of Nutrition Education and Behavior.*

[Teachers’ perceptions indicate success for harvest of the month nutrition education program](https://scholar.google.com/scholar?oi=bibs&cluster=6181972192247665776&btnI=1&hl=en) (2012). Kristen Evans, Keiko Goto, Cindy Wolff, **Martin Frigaard**, Stephanie Bianco-Simeral. *California Journal of Health Promotion*.

[Discrepancies Among Student School Lunch Preferences, Menu Options, and Consumption Patterns in a Low-Income Northern California High-School](https://scholar.google.com/scholar?oi=bibs&cluster=11533561784794024897&btnI=1&hl=en) (2011). Kelly Fiori, Cindy Wolff, Keiko Goto, **Martin Frigaard**, Kenny Chan, Stephanie Bianco-Simeral. *California Journal of Health Promotion*.

<center>
### Hypertension
</center>

[Identifying Red Flags: Using Anthropometry Measures to Screen for Elevated Blood Pressure Risk in Children](https://doi.org/10.1177/1941406412470719) (2013). **Martin Frigaard**, Keiko Goto, Cindy Wolff, Stephanie Bianco-Simeral, Thomas Fahey. *ICAN: Infant, Child, & Adolescent Nutrition*.

[Associations Between Obesity and Elevated Blood Pressure Among Children in Five Low-Income Northern California Elementary Schools](https://scholarworks.calstate.edu/concern/theses/pr76f411b) (2012). **Martin Frigaard**, Stephanie Bianco-Simeral, Cindy Wolff, Thomas D. Fahey, George David Swanson, Kevin G. Patton. *Masters Thesis, California State University, Chico.*

[A longitudinal study of overweight, elevated blood pressure, and acanthosis nigricans among low-income middle school students](https://doi.org/10.1177/1059840511428615) (2012). Dana Kopping, Holly Nevarez, Keiko Goto, Irene Morgan, **Martin Frigaard**, Cindy Wolff. *The Journal of School Nursing*.